name: Docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install lark-parser
      - run: rm docs/api.md
      - run: make docs/api.md
      - run: git diff --exit-code docs
