name: Test

on: [push, pull_request]

jobs:
  #  docs:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: actions/setup-python@v2
  #      - run: python -m pip install lark-parser
  #      - run: rm docs/api.md
  #      - run: make docs/api.md
  #      - run: git diff --exit-code docs
  #
  #  ubuntu:
  #    runs-on: ubuntu-latest
  #    strategy:
  #      matrix:
  #        arch: [amd64, i386]
  #    steps:
  #      - uses: actions/checkout@v2
  #      - name: Login to repository
  #        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "$GITHUB_ACTOR" --password-stdin
  #      - name: Test
  #        run: docker run -v ${PWD}:/github/workspace docker.pkg.github.com/bytesandbrains/h3-pg/test:${{ matrix.arch }}

  # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: cmake --install build --component extension
      - run: cmake --build build --target installcheck
